### ISSUE TITLE
カードコンポーネントが動作するreactアプリを試作する

### ISSUE THREAD

**Issue by jiro2020** [jiro2020/lifelog#2]
## 概要

- node.js の docker image に関する概要とベストプラクティス
   - https://nodejs.org/ja/docs/guides/nodejs-docker-webapp/
   - https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md

## 以下学んだこと
- Material UI の設定用の参考
   - https://dev.classmethod.jp/articles/react-material-ui/
- `@types` 付きのパッケージはTypeScriptの型定義、そのため `npm install --save-dev` のように `devDependencies` に追加する
- `<Swith>` は `<Routes>` に変更された
   - https://stackoverflow.com/questions/63124161/attempted-import-error-switch-is-not-exported-from-react-router-dom
- コンテナ内のアプリ編集をホットリロードさせるためには `node-dev` などを用いると良い（`.tsx` 対象であれば `ts-node-dev` ）
   - https://stackoverflow.com/questions/37328867/how-to-restart-node-on-a-docker-container-without-restarting-the-whole-container
   - https://qiita.com/sa9ra4ma/items/67ab5ac6fea3e5f065b0
- `npm run` は `npm start run` のエイリアス
   - https://yanor.net/wiki/?Node.js/npm/npm+run+start%E3%81%A8npm+start%E3%81%AE%E9%81%95%E3%81%84

**Comment by jiro2020** [comment]
- `npm-run ts-node-dev` で以下のエラーに。下記のURLの情報が役立つが、そもそも tsconfig.json など Tyepscript 周りの理解度を上げたい

https://stackoverflow.com/questions/58273824/typescript-cannot-use-import-statement-outside-a-module
https://github.com/TypeStrong/ts-node#module-type-overrides
https://github.com/wclr/ts-node-dev#issues

```
[INFO] 14:25:35 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
(node:3507) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/node/app/react-app/src/HomePage.tsx:1
import { Fragment as _Fragment, jsx as _jsx } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._compile (/home/node/app/react-app/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-6712553656353624.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-6712553656353624.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-6712553656353624.js:71:20)
    at Object.nodeDevHook [as .tsx] (/home/node/app/react-app/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
[ERROR] 14:25:42 SyntaxError: Cannot use import statement outside a module
```
